export const predictionConsoleColumns = [
  { name: "id", required: "Optional", type: "string / number", description: "Student or row identifier used only for display and exports." },
  { name: "avg_score_until_cutoff", required: "Required", type: "number", description: "Average assessment score available at the selected prediction checkpoint." },
  { name: "submitted_assessments_until_cutoff", required: "Required", type: "number", description: "Count of submitted assessments before the cutoff." },
  { name: "arab_active_days_equivalent_until_cutoff", required: "Required", type: "number", description: "Active learning days converted to the course timeline scale." },
  { name: "avg_submission_delay_arab_days_until_cutoff", required: "Required", type: "number", description: "Average submission delay in course-day units. Higher values usually increase concern." },
  { name: "homepage", required: "Required", type: "number", description: "Homepage VLE clicks before the cutoff." },
  { name: "age_band", required: "Required", type: "category", description: "Learner age band, for example 0-35, 35-55, or 55<=." },
  { name: "forumng", required: "Required", type: "number", description: "Forum activity click count." },
  { name: "unique_sites_until_cutoff", required: "Required", type: "number", description: "Number of distinct VLE sites visited before the cutoff." },
  { name: "unique_activity_types_until_cutoff", required: "Required", type: "number", description: "Number of distinct learning activity types used before the cutoff." },
  { name: "clicks_per_active_day_until_cutoff", required: "Required", type: "number", description: "Average click intensity on days where the learner was active." },
  { name: "resource", required: "Required", type: "number", description: "Resource activity clicks." },
  { name: "subpage", required: "Required", type: "number", description: "Subpage activity clicks." },
  { name: "url", required: "Required", type: "number", description: "URL activity clicks." },
  { name: "oucontent", required: "Required", type: "number", description: "Course-content activity clicks." },
  { name: "quiz", required: "Required", type: "number", description: "Quiz activity clicks." },
  { name: "highest_education", required: "Required", type: "category", description: "Highest education level, such as HE Qualification or Lower Than A Level." },
  { name: "imd_band", required: "Required", type: "category", description: "Index of Multiple Deprivation band, such as 0-10% or 90-100%." },
  { name: "gender", required: "Optional", type: "category", description: "Can be included for dashboard context, but the current model does not require it." },
];

export const intelligenceLabColumns = [
  { name: "code_module", required: "Recommended", type: "category", description: "Course module code used for module-level EDA." },
  { name: "code_presentation", required: "Recommended", type: "category", description: "Course presentation or semester identifier." },
  { name: "id_student", required: "Recommended", type: "number", description: "Unique learner identifier." },
  { name: "gender", required: "Recommended", type: "category", description: "Learner gender used in demographic profile charts." },
  { name: "region", required: "Optional", type: "category", description: "Learner region for demographic exploration." },
  { name: "highest_education", required: "Recommended", type: "category", description: "Education band used in demographic and feature-readiness views." },
  { name: "imd_band", required: "Recommended", type: "category", description: "Socio-economic deprivation band." },
  { name: "age_band", required: "Recommended", type: "category", description: "Age group for demographic distribution." },
  { name: "num_of_prev_attempts", required: "Optional", type: "number", description: "Previous attempts for the same course/module." },
  { name: "studied_credits", required: "Optional", type: "number", description: "Study load in credits." },
  { name: "disability", required: "Optional", type: "category", description: "Disability flag when available." },
  { name: "final_result", required: "Recommended", type: "category", description: "Original course outcome, such as Pass, Distinction, Fail, or Withdrawn." },
  { name: "target", required: "Recommended", type: "category", description: "Risk target label, typically at_risk or successful." },
  { name: "module_presentation_length", required: "Optional", type: "number", description: "Duration of the module presentation in days." },
  { name: "total_clicks", required: "Recommended", type: "number", description: "Total VLE clicks across the course window." },
  { name: "total_active_days", required: "Recommended", type: "number", description: "Number of days with VLE activity." },
  { name: "vle_module_presentation_length", required: "Optional", type: "number", description: "VLE timeline length used for ratio calculations." },
  { name: "unique_sites", required: "Recommended", type: "number", description: "Distinct VLE sites visited." },
  { name: "unique_activity_types", required: "Recommended", type: "number", description: "Distinct VLE activity categories used." },
  { name: "clicks_first_25", required: "Optional", type: "number", description: "Clicks during the first quarter of the course." },
  { name: "clicks_first_50", required: "Optional", type: "number", description: "Clicks during the first half of the course." },
  { name: "clicks_last_25", required: "Optional", type: "number", description: "Clicks during the final quarter of the course." },
  { name: "clicks_per_active_day", required: "Recommended", type: "number", description: "Click intensity on active days." },
  { name: "active_days_ratio", required: "Recommended", type: "number", description: "Share of course days where the learner was active." },
  { name: "arab_active_days_equivalent", required: "Recommended", type: "number", description: "Active days mapped to the normalized course-day scale." },
  { name: "avg_score", required: "Recommended", type: "number", description: "Average assessment score across submitted work." },
  { name: "min_score", required: "Optional", type: "number", description: "Lowest assessment score." },
  { name: "max_score", required: "Optional", type: "number", description: "Highest assessment score." },
  { name: "submitted_assessments", required: "Recommended", type: "number", description: "Number of submitted assessments." },
  { name: "late_submissions", required: "Optional", type: "number", description: "Count of late submissions." },
  { name: "avg_submission_delay", required: "Recommended", type: "number", description: "Average submission delay in raw timeline units." },
  { name: "avg_assessment_relative_time", required: "Optional", type: "number", description: "Average scheduled assessment time as a course-length ratio." },
  { name: "avg_submitted_relative_time", required: "Optional", type: "number", description: "Average submitted time as a course-length ratio." },
  { name: "avg_assessment_arab_day", required: "Optional", type: "number", description: "Average assessment deadline on normalized course-day scale." },
  { name: "avg_submitted_arab_day", required: "Optional", type: "number", description: "Average submission day on normalized course-day scale." },
  { name: "avg_submission_delay_relative", required: "Optional", type: "number", description: "Submission delay as a relative course-length value." },
  { name: "avg_submission_delay_arab_days", required: "Recommended", type: "number", description: "Submission delay on normalized course-day scale." },
  { name: "assessments_first_50", required: "Optional", type: "number", description: "Assessments available in the first half of the course." },
  { name: "workload_ratio", required: "Optional", type: "number", description: "Credit workload normalized against a reference load." },
  { name: "workload_level", required: "Optional", type: "category", description: "Readable workload bucket, such as light or very_high." },
];

export const workspaceCards = [
  {
    id: "predict",
    title: "Prediction Console",
    eyebrow: "Model scoring",
    summary: "Use this path when you already have the 17 model-ready features for one student or a batch of students.",
    output: "Returns predicted risk score, risk band, model confidence, batch summaries, and a downloadable enriched prediction file.",
    bestFor: ["Single-student scoring", "Batch risk review", "Fast intervention queue"],
  },
  {
    id: "eda",
    title: "Intelligence Lab",
    eyebrow: "Dataset exploration",
    summary: "Use this path when you want to inspect a broader engineered student-course dataset before or after prediction.",
    output: "Shows outcome distribution, demographic profile, assessment score patterns, activity mix, and feature readiness.",
    bestFor: ["Notebook-style EDA", "Cohort explanation", "Dataset quality checks"],
  },
];
